module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LCOKj4TGA2y2q39hdGA3ZC',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://dbv5.pages.dev/song/IMG-20251214-WA0238.jpg',
    NEWSLETTER_JID: '120363421928318889@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'Movie-Zoone',
    OWNER_NAME: 'Yasiya',
    OWNER_NUMBER: '+94774707462',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> Movie-Zoone',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBnBHO7dmeXOGO3Qt24',
};
